### ISSUE TITLE
Searching by custom field

### ISSUE THREAD

**Issue by barnaclebarnes** [basecrm/basecrm-ruby#40]
How do I search for a contact with a custom field? I want to be able to search alternative email addresses for contacts to see if I can get a match. I am guessing however that even if I could filter by custom fields that alternate email addresses are not supported for searching? Is there **any** way I can search for a contact via an alternative email address?

**Comment by grzegorz-mysliwiec** [comment]
Do you mean searching by custom field with email type which you use to keep alternate email address?

**Comment by barnaclebarnes** [comment]
@grzegorz-mysliwiec Yes - Which, now looking at it, isn't possible with the API? Seems a bit strange that you can search on text fields but not email addresses.

**Comment by pharazon** [comment]
Hello, after a long debugging I finally tried it out on curl command line, and read the documentation:
https://developers.getbase.com/docs/rest/articles/requests
It says: 
**In addition to standard attributes, we support custom fields filtering. In order to use it, you need set the custom field to as Filterable in the custom field settings.** 

So, you need to go to BaseCRM Settings -> Contacts and click on "Filterable". After this I got the rid of the error message: 
The request query parameter 'custom_fields/Name#1' is malformed, missing, or has an invalid value (is an unexpected parameter)
